name: HTML CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  html-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Run HTML Lint
        run: htmlhint index.html || true
